version: "3"
services:
  api:
    environment:
      JWT_SECRET: $JWT_SECRET
      REDIS_URL: $REDIS_URL
    build: .
    volumes:
      - .:/app
    links:
      - "db:mysql"
      - "redis:redis"
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $TYPEORM_DATABASE
      MYSQL_USER: $TYPEORM_USERNAME
      MYSQL_PASSWORD: $TYPEORM_PASSWORD
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - .docker-redis:/data
    restart: always
